info:
  project:
    version: @project.version@

# Put healthcheck.enabled=true here instead of in bootstrap.yml.
# Otherwise the status in Eureka always get unknown error.
# Other configuration need to be in bootstrap if we set spring.cloud.discovery.enabled=true
eureka:
  client:
    healthcheck:
      enabled: true

#mybatis:
#  config-location: classpath:mybatis-config.xml

# swagger
application:
  swagger:
    enable: ${SWAGGER_ENABLED:true}
    default-include-pattern: /api/.*
    title: @project.artifactId@
    description: API documentation
    version: v1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license:
    license-url: