server:
  port: ${SERVER_PORT:8123}
  undertow:
    io-threads: 8
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true


zipkin:
  collector:
    rabbitmq:
      addresses: ${RABBIT_HOST:192.168.1.101}:${RABBIT_PORT:5672}
      username: ${RABBIT_USERNAME:sid}
      password: ${RABBIT_PASSWORD:111111}
      queue: zipkin
      virtual-host: ${RABBIT_VHOST:guilin}

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
      roles: SYSTEM
    metrics:
      enabled: true
    hystrix:
      stream:
        enabled: false
  metrics:
    web:
      server:
        auto-time-requests: false
  info:
    git:
      mode: full

info:
  project:
    version: @project.version@

# Put eureka.client.healthcheck.enabled=true application.yml instead of in bootstrap.yml.
# Otherwise the status in Eureka always get unknown error.
# eureka.client.serviceUrl.defaultZone need to be set in
# bootstrap.yml if set spring.cloud.discovery.enabled=true
eureka:
  instance:
    statusPageUrlPath: ${management.endpoints.web.base-path}/info
    healthCheckUrlPath: ${management.endpoints.web.base-path}/health
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.id}}
  client:
    healthcheck:
      enabled: true
    fetchRegistry: true
    registerWithEureka: true
    preferSameZoneEureka: true
    registryFetchIntervalSeconds: 30

logging:
  level:
    ROOT: info
