spring:
  cloud:
    gateway:
      routes:
        - id: mobile_api_route
          uri: lb://facade-service
          predicates:
            - Path=/mobile/**
          filters:
#            - RewritePath=/mobile/(?<segment>.*), /$\{segment}
            - StripPrefix=1
        - id: uaa_route
          uri: lb://uaa-service
          predicates:
            - Path=/uaa/**
