spring:
  cloud:
    gateway:
      routes:
        - id: add_request_header_route
          uri: http://localhost:8082
          predicates:
            - After=2019-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
            - AddRequestParameter=foo, bar
            - AddResponseHeader=X-Response-Foo, Bar
            - PrefixPath=/mypath
            - PreserveHostHeader
