info:
  project:
    version: @project.version@

# Put healthcheck.enabled=true here instead of in bootstrap.yml.
# Otherwise the status in Eureka always get unknown error.
# Other configuration need to be in bootstrap if we set spring.cloud.discovery.enabled=true
eureka:
  client:
    healthcheck:
      enabled: true